import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Sparkles,
    Send,
    FileText,
    BarChart3,
    RefreshCcw,
    CheckCircle2,
    AlertTriangle,
    Lightbulb,
    ArrowRight,
    Plus,
    Calendar,
    Users,
    Clock,
    MessageSquare,
    Mic
} from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { aiService } from '@/services/ai.service';
import { taskService } from '@/services/task.service';
import { projectService } from '@/services/project.service';
import { useUI } from '@/context/UIContext';

const AIAssistant = () => {
    const { user } = useAuth();
    const { showToast } = useUI();
    const [activeTab, setActiveTab] = useState<'generate' | 'transcript' | 'summary' | 'chat' | 'suggest' | 'plan'>(
        'transcript'
    );
    const [input, setInput] = useState('');
    const [meetingTitle, setMeetingTitle] = useState('');
    const [pipeline, setPipeline] = useState('General');
    const [isGenerating, setIsGenerating] = useState(false);
    const [isPopulating, setIsPopulating] = useState(false);
    const [result, setResult] = useState<any>(null);
    const [projects, setProjects] = useState<any[]>([]);
    const [selectedProjectId, setSelectedProjectId] = useState<string>('');
    const [addingTaskId, setAddingTaskId] = useState<number | null>(null);
    const [isListening, setIsListening] = useState(false);
    const [chatInput, setChatInput] = useState('');
    const [chatLoading, setChatLoading] = useState(false);
    const [chatMessages, setChatMessages] = useState<any[]>([
        {
            id: 'welcome',
            role: 'assistant',
            content: 'Hi, I am your AI management assistant. Ask me about planning, priorities, or risks.'
        }
    ]);

    useEffect(() => {
        const fetchProjects = async () => {
            try {
                const data = await projectService.getProjects();
                setProjects(data);
                if (data.length > 0) setSelectedProjectId(data[0].id);
            } catch (error) {
                console.error('Error fetching projects:', error);
            }
        };
        fetchProjects();
    }, []);

    const handleChatSend = async (rawMessage: string) => {
        const text = rawMessage.trim();
        if (!text) return;

        const userMsg = {
            id: `u-${Date.now()}`,
            role: 'user',
            content: text
        };
        const nextMessages = [...chatMessages, userMsg];
        setChatMessages(nextMessages);
        setChatInput('');
        setChatLoading(true);

        try {
            const response = await aiService.chat(
                nextMessages.map(m => ({
                    role: m.role,
                    content: m.content
                }))
            );
            const assistantContent =
                response?.content ||
                (response as any)?.message ||
                (typeof response === 'string' ? response : 'No response from AI assistant.');

            setChatMessages(prev => [
                ...prev,
                {
                    id: `a-${Date.now()}`,
                    role: 'assistant',
                    content: assistantContent
                }
            ]);
        } catch (error) {
            console.error('Chat error:', error);
            showToast('Chat assistant is unavailable right now', 'error');
            setChatMessages(prev => [
                ...prev,
                {
                    id: `a-err-${Date.now()}`,
                    role: 'assistant',
                    content: 'I could not process that request. Please try again.'
                }
            ]);
        } finally {
            setChatLoading(false);
        }
    };

    const handleCreateTask = async (title: string, index: number, details?: any) => {
        if (!selectedProjectId || !user) return;
        setAddingTaskId(index);
        try {
            const description = details?.assignee
                ? `${details.description || 'Generated by AI Assistant'}\n\nSuggested assignee: ${details.assignee}`
                : details?.description || 'Generated by AI Assistant';

            let dueDate;
            if (details?.deadline) {
                const d = new Date(details.deadline);
                dueDate = isNaN(d.getTime()) ? new Date(Date.now() + 86400000).toISOString() : d.toISOString();
            } else {
                dueDate = new Date(Date.now() + 86400000).toISOString();
            }

            await taskService.createTask({
                title,
                description,
                projectId: selectedProjectId,
                assignedTo: user.id,
                status: 'To Do',
                priority: 'Medium',
                dueDate: dueDate
            });
            showToast(`Task "${title}" added to project`);
        } catch (error) {
            console.error('Error creating task:', error);
            showToast('Failed to create task', 'error');
        } finally {
            setAddingTaskId(null);
        }
    };

    const handlePopulateAllTasks = async () => {
        if (!result?.tasks || !selectedProjectId || !user) return;
        setIsPopulating(true);
        try {
            for (let i = 0; i < result.tasks.length; i++) {
                const task = result.tasks[i];
                const title = typeof task === 'string' ? task : task.title;
                await handleCreateTask(title, i + 1000, typeof task === 'object' ? task : null);
            }
            showToast('All tasks populated successfully');
        } catch (err) {
            console.error('Error populating tasks:', err);
            showToast('Error populating some tasks', 'error');
        } finally {
            setIsPopulating(false);
        }
    };

    const handleAction = async () => {
        if ((activeTab !== 'summary' && !input.trim()) || !user) return;

        setIsGenerating(true);
        setResult(null);

        try {
            let response;
            const projectTasks = selectedProjectId ? await taskService.getTasks(selectedProjectId) : [];

            if (activeTab === 'generate') {
                response = await aiService.generateTasks(input, user.id);
            } else if (activeTab === 'transcript') {
                const contextInput = `Meeting Title: ${meetingTitle}\nPipeline: ${pipeline}\n\nTranscript:\n${input}`;
                response = await aiService.extractTasksFromTranscript(contextInput, user.id);
            } else if (activeTab === 'suggest') {
                if (projectTasks.length === 0) {
                    showToast('Project has no tasks to analyze', 'error');
                    setIsGenerating(false);
                    return;
                }
                response = await aiService.suggestTasks(projectTasks);
            } else if (activeTab === 'plan') {
                const selectedProject = projects.find(p => p.id === selectedProjectId);
                response = await aiService.generateProjectPlan({
                    name: selectedProject?.name,
                    description: selectedProject?.description
                });
            } else {
                if (!selectedProjectId) {
                    showToast('Please select a project for analysis', 'error');
                    setIsGenerating(false);
                    return;
                }
                response = await aiService.getProjectSummary(selectedProjectId, projectTasks, user.id);
            }

            if (!response) {
                showToast('AI assistant did not return any insights', 'error');
            } else {
                setResult(response);
                showToast('AI analysis complete');
            }
        } catch (error) {
            console.error('AI Error:', error);
            showToast('AI engine encountered an error', 'error');
        } finally {
            setIsGenerating(false);
        }
    };

    const toggleVoiceRecognition = () => {
        const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
        if (!SpeechRecognition) {
            showToast('Voice recognition not supported in this browser', 'error');
            return;
        }

        if (isListening) {
            setIsListening(false);
            return;
        }

        const recognition = new SpeechRecognition();
        recognition.lang = 'en-US';
        recognition.interimResults = false;
        recognition.maxAlternatives = 1;

        recognition.onstart = () => {
            setIsListening(true);
            showToast('Neural Voice Uplink active...', 'info');
        };

        recognition.onresult = (event: any) => {
            const transcript = event.results[0][0].transcript;
            if (activeTab === 'chat') {
                handleChatSend(transcript);
            } else {
                setInput(prev => prev + ' ' + transcript);
            }
            setIsListening(false);
        };

        recognition.onerror = () => {
            setIsListening(false);
            showToast('Voice recognition failed', 'error');
        };

        recognition.onend = () => {
            setIsListening(false);
        };

        recognition.start();
    };

    const tabs = [
        { id: 'transcript', label: 'Meeting Extract', icon: FileText, desc: 'Identify action items from transcripts.' },
        {
            id: 'generate',
            label: 'Generate Tasks',
            icon: Sparkles,
            desc: 'Turn ideas into actionable task lists instantly.'
        },
        {
            id: 'suggest',
            label: 'Optimize Priority',
            icon: CheckCircle2,
            desc: 'AI suggests priorities and realistic deadlines.'
        },
        {
            id: 'plan',
            label: 'Strategic Plan',
            icon: Lightbulb,
            desc: 'Generate a comprehensive project execution strategy.'
        },
        {
            id: 'summary',
            label: 'Project Health',
            icon: BarChart3,
            desc: 'Assess project status, risks, and next steps.'
        },
        {
            id: 'chat',
            label: 'Chat Assistant',
            icon: MessageSquare,
            desc: 'Ask questions or discuss your project strategies.'
        }
    ];

    return (
        <div className='max-w-5xl mx-auto space-y-8 md:space-y-10 pb-20'>
            <div className='relative overflow-hidden rounded-3xl bg-gradient-to-br from-primary/10 via-transparent to-accent/10 p-6 md:p-8 border border-border'>
                <div className='relative z-10 flex flex-col items-center text-center space-y-4'>
                    <motion.div
                        initial={{ scale: 0.9, opacity: 0 }}
                        animate={{ scale: 1, opacity: 1 }}
                        className='inline-flex items-center gap-2 bg-primary/10 text-primary px-4 py-1.5 rounded-full font-bold text-[10px] md:text-xs tracking-wider uppercase border border-primary/20'
                    >
                        <Sparkles size={14} />
                        <span>AI Management Engine</span>
                    </motion.div>
                    <h1 className='text-3xl md:text-5xl font-black tracking-tight text-foreground leading-tight'>
                        How can I accelerate your{' '}
                        <span className='text-primary underline decoration-primary/30 underline-offset-8'>
                            workflow
                        </span>
                        ?
                    </h1>
                    <p className='text-muted-foreground max-w-xl mx-auto text-base md:text-lg'>
                        Empower your team with autonomous project coordination and intelligent insights.
                    </p>
                </div>
                <div className='absolute top-0 left-1/4 w-64 h-64 bg-primary/5 rounded-full blur-[100px]'></div>
                <div className='absolute bottom-0 right-1/4 w-64 h-64 bg-accent/5 rounded-full blur-[100px]'></div>
            </div>

            <div className='grid grid-cols-1 xs:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 md:gap-4'>
                {tabs.map(tab => (
                    <button
                        key={tab.id}
                        onClick={() => {
                            setActiveTab(tab.id as any);
                            setResult(null);
                            setInput('');
                        }}
                        className={`p-4 md:p-6 rounded-2xl text-left transition-all group relative overflow-hidden ${
                            activeTab === tab.id
                                ? 'bg-primary/5 border border-primary/30 text-primary'
                                : 'bg-card border border-border text-muted-foreground hover:border-primary/30 hover:text-foreground'
                        }`}
                    >
                        {activeTab === tab.id && (
                            <motion.div
                                layoutId='tab-active'
                                className='absolute inset-0 bg-primary/5 -z-10'
                            />
                        )}
                        <tab.icon
                            className={`mb-3 md:mb-4 transition-transform group-hover:scale-110 shrink-0 ${activeTab === tab.id ? 'text-primary' : ''}`}
                            size={20}
                        />
                        <h3 className='font-bold text-xs md:text-sm mb-1 transition-colors whitespace-nowrap overflow-hidden text-ellipsis'>
                            {tab.label}
                        </h3>
                    </button>
                ))}
            </div>

            <div className='card space-y-6 md:space-y-8 relative overflow-hidden shadow-xl p-5 md:p-8'>
                {activeTab === 'chat' ? (
                    <div className='flex flex-col h-[500px] md:h-[600px] -m-5 md:-m-8'>
                        <div className='flex-1 overflow-y-auto p-4 md:p-6 space-y-4 bg-card'>
                            {chatMessages.map((message: any) => (
                                <div
                                    key={message.id}
                                    className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
                                >
                                    <div
                                        className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                                            message.role === 'user'
                                                ? 'bg-primary text-primary-foreground'
                                                : 'bg-secondary text-foreground border border-border'
                                        }`}
                                    >
                                        {message.content}
                                    </div>
                                </div>
                            ))}
                            {chatLoading && (
                                <div className='flex justify-start'>
                                    <div className='rounded-2xl px-4 py-3 text-sm bg-secondary text-muted-foreground border border-border'>
                                        Thinking...
                                    </div>
                                </div>
                            )}
                        </div>
                        <form
                            onSubmit={e => {
                                e.preventDefault();
                                handleChatSend(chatInput);
                            }}
                            className='border-t border-border bg-background p-3 md:p-4 flex items-center gap-2'
                        >
                            <input
                                value={chatInput}
                                onChange={e => setChatInput(e.target.value)}
                                placeholder='Ask your AI assistant...'
                                className='input-field h-11 flex-1'
                                disabled={chatLoading}
                            />
                            <button
                                type='submit'
                                disabled={chatLoading || !chatInput.trim()}
                                className='btn-primary h-11 px-5'
                            >
                                Send
                            </button>
                        </form>
                    </div>
                ) : (
                    <>
                        <div className='space-y-4'>
                            <div className='flex items-center justify-between'>
                                <label className='text-[10px] md:text-xs font-black text-muted-foreground uppercase tracking-[0.2em]'>
                                    {activeTab === 'generate'
                                        ? 'Vision'
                                        : activeTab === 'transcript'
                                          ? 'New Analysis'
                                          : 'Insights'}
                                </label>
                                <span className='hidden sm:inline text-[10px] text-muted-foreground italic'>
                                    CMD + Enter to process
                                </span>
                            </div>

                            {activeTab === 'transcript' ? (
                                <div className='space-y-6'>
                                    <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
                                        <div className='space-y-2'>
                                            <label className='text-[9px] md:text-[10px] uppercase font-bold text-muted-foreground px-1'>
                                                Pipeline
                                            </label>
                                            <select
                                                value={pipeline}
                                                onChange={e => setPipeline(e.target.value)}
                                                className='input-field h-11 py-0'
                                            >
                                                <option value='General'>General / Unassigned</option>
                                                <option value='Design'>Design Pipeline</option>
                                                <option value='Development'>Development Pipeline</option>
                                                <option value='Marketing'>Marketing Pipeline</option>
                                            </select>
                                        </div>
                                        <div className='space-y-2'>
                                            <label className='text-[9px] md:text-[10px] uppercase font-bold text-muted-foreground px-1'>
                                                Meeting Title
                                            </label>
                                            <input
                                                type='text'
                                                value={meetingTitle}
                                                onChange={e => setMeetingTitle(e.target.value)}
                                                placeholder='Weekly Sync, Kickoff, etc.'
                                                className='input-field h-11'
                                            />
                                        </div>
                                    </div>

                                    <div className='space-y-2'>
                                        <label className='text-[9px] md:text-[10px] uppercase font-bold text-muted-foreground px-1'>
                                            Project
                                        </label>
                                        <select
                                            value={selectedProjectId}
                                            onChange={e => setSelectedProjectId(e.target.value)}
                                            className='input-field h-11 py-0'
                                        >
                                            <option value=''>Select project...</option>
                                            {projects.map(p => (
                                                <option
                                                    key={p.id}
                                                    value={p.id}
                                                >
                                                    {p.name}
                                                </option>
                                            ))}
                                        </select>
                                    </div>

                                    <div className='space-y-2'>
                                        <label className='text-[9px] md:text-[10px] uppercase font-bold text-muted-foreground px-1'>
                                            Transcript
                                        </label>
                                        <textarea
                                            value={input}
                                            onChange={e => setInput(e.target.value)}
                                            placeholder='Paste meeting transcript here to extract action items...'
                                            className='input-field min-h-[180px] md:min-h-[220px] text-sm md:text-base resize-none'
                                        />
                                    </div>
                                </div>
                            ) : activeTab !== 'summary' ? (
                                <div className='space-y-4'>
                                    <div className='space-y-2'>
                                        <label className='text-[9px] md:text-[10px] uppercase font-bold text-muted-foreground px-1'>
                                            Target Project
                                        </label>
                                        <select
                                            value={selectedProjectId}
                                            onChange={e => setSelectedProjectId(e.target.value)}
                                            className='input-field h-10 py-0'
                                        >
                                            <option value=''>Select project...</option>
                                            {projects.map(p => (
                                                <option
                                                    key={p.id}
                                                    value={p.id}
                                                >
                                                    {p.name}
                                                </option>
                                            ))}
                                        </select>
                                    </div>
                                    <textarea
                                        value={input}
                                        onChange={e => setInput(e.target.value)}
                                        placeholder={
                                            activeTab === 'generate'
                                                ? 'Describe what you want to build...'
                                                : 'Paste transcript here...'
                                        }
                                        className='input-field min-h-[150px] md:min-h-[180px] text-sm md:text-base resize-none'
                                    />
                                </div>
                            ) : (
                                <div className='grid grid-cols-1 sm:grid-cols-2 gap-4'>
                                    <div className='p-4 rounded-xl bg-secondary border border-border flex items-center justify-between'>
                                        <div className='min-w-0'>
                                            <p className='text-[9px] md:text-[10px] uppercase font-bold text-muted-foreground mb-1'>
                                                Target Project
                                            </p>
                                            <select
                                                value={selectedProjectId}
                                                onChange={e => setSelectedProjectId(e.target.value)}
                                                className='bg-transparent font-bold text-foreground focus:outline-none w-full truncate'
                                            >
                                                {projects.map(p => (
                                                    <option
                                                        key={p.id}
                                                        value={p.id}
                                                        className='bg-card'
                                                    >
                                                        {p.name}
                                                    </option>
                                                ))}
                                            </select>
                                        </div>
                                        <ArrowRight
                                            className='text-muted-foreground shrink-0'
                                            size={16}
                                        />
                                    </div>
                                    <div className='p-4 rounded-xl bg-secondary border border-border flex items-center justify-between'>
                                        <div>
                                            <p className='text-[9px] md:text-[10px] uppercase font-bold text-muted-foreground mb-1'>
                                                Period
                                            </p>
                                            <p className='font-bold text-foreground whitespace-nowrap'>Last 30 Days</p>
                                        </div>
                                        <Calendar
                                            className='text-muted-foreground shrink-0'
                                            size={16}
                                        />
                                    </div>
                                </div>
                            )}
                        </div>

                        <div className='flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-border'>
                            <div className='flex items-center gap-3'>
                                <div className='flex -space-x-1.5'>
                                    {[1, 2].map(i => (
                                        <div
                                            key={i}
                                            className='w-6 h-6 rounded-full bg-primary/10 border border-background flex items-center justify-center text-[8px] font-bold text-primary'
                                        >
                                            AI
                                        </div>
                                    ))}
                                </div>
                                <p className='text-[9px] md:text-[10px] text-muted-foreground font-medium'>
                                    Models optimized for management
                                </p>
                            </div>
                            <div className='flex items-center gap-2 w-full sm:w-auto'>
                                <button
                                    type='button'
                                    onClick={toggleVoiceRecognition}
                                    className={`w-12 h-12 rounded-xl flex items-center justify-center transition-all shrink-0 ${isListening ? 'bg-rose-500 text-white animate-pulse' : 'bg-secondary text-muted-foreground hover:text-primary'}`}
                                >
                                    <Mic size={20} />
                                </button>
                                {activeTab === 'transcript' && (
                                    <button
                                        onClick={async () => {
                                            if (!input.trim()) return;
                                            setIsGenerating(true);
                                            try {
                                                const res = await aiService.summarizeTranscript(input);
                                                setResult({ ...result, summary: res.summary });
                                                showToast('Summary generated');
                                            } catch (err) {
                                                showToast('Failed to generate summary', 'error');
                                            } finally {
                                                setIsGenerating(false);
                                            }
                                        }}
                                        disabled={isGenerating || !input.trim()}
                                        className='btn-secondary h-12 px-6 text-xs whitespace-nowrap'
                                    >
                                        AI Summarize
                                    </button>
                                )}
                                <button
                                    onClick={handleAction}
                                    disabled={isGenerating || (activeTab !== 'summary' && !input.trim())}
                                    className='btn-primary flex-1 sm:flex-none px-6 md:px-10 py-3 text-sm h-12'
                                >
                                    {isGenerating ? (
                                        <>
                                            <RefreshCcw
                                                className='animate-spin'
                                                size={16}
                                            />
                                            <span className='text-xs'>Processing...</span>
                                        </>
                                    ) : (
                                        <>
                                            <Send size={16} />
                                            <span className='text-xs'>
                                                {activeTab === 'transcript' ? 'Extract Insights' : 'Execute'}
                                            </span>
                                        </>
                                    )}
                                </button>
                            </div>
                        </div>
                    </>
                )}
            </div>

            <AnimatePresence mode='wait'>
                {result && (
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.95 }}
                        className='space-y-6 md:space-y-8 pb-24'
                    >
                        {result.summary && (
                            <div className='bg-primary/5 border border-primary/20 p-6 rounded-2xl'>
                                <h3 className='text-sm font-bold text-primary mb-2 flex items-center gap-2'>
                                    <FileText size={16} />
                                    Meeting Summary
                                </h3>
                                <p className='text-sm text-foreground/80 leading-relaxed'>{result.summary}</p>
                            </div>
                        )}

                        <div className='flex items-center justify-between gap-4'>
                            <div className='flex items-center gap-3 min-w-0'>
                                <div className='w-9 h-9 md:w-10 md:h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary border border-primary/20 shrink-0'>
                                    <Sparkles size={18} />
                                </div>
                                <div className='min-w-0'>
                                    <h2 className='text-xl md:text-2xl font-black text-foreground truncate'>
                                        {activeTab === 'transcript' ? 'Action Items' : 'Intelligent Output'}
                                    </h2>
                                </div>
                            </div>
                            <div className='flex items-center gap-4'>
                                {activeTab === 'transcript' && result?.tasks?.length > 0 && (
                                    <button
                                        onClick={handlePopulateAllTasks}
                                        disabled={isPopulating}
                                        className='btn-primary py-1.5 px-4 text-[10px] font-bold uppercase tracking-widest whitespace-nowrap'
                                    >
                                        {isPopulating ? 'Populating...' : 'Populate All Tasks'}
                                    </button>
                                )}
                                <button
                                    onClick={() => setResult(null)}
                                    className='text-muted-foreground hover:text-foreground transition-colors text-[10px] font-bold uppercase tracking-widest whitespace-nowrap'
                                >
                                    Clear
                                </button>
                            </div>
                        </div>

                        <div className='grid grid-cols-1 gap-4'>
                            {activeTab === 'generate' && result?.tasks && (
                                <div className='grid grid-cols-1 sm:grid-cols-2 gap-4'>
                                    {result.tasks.map((task: string, i: number) => (
                                        <motion.div
                                            key={i}
                                            initial={{ opacity: 0, x: -20 }}
                                            animate={{ opacity: 1, x: 0 }}
                                            transition={{ delay: i * 0.05 }}
                                            className='bg-card border border-border p-4 md:p-5 rounded-2xl flex items-center justify-between group hover:border-primary/30 transition-all shadow-sm'
                                        >
                                            <div className='flex items-center gap-3 md:gap-4 min-w-0'>
                                                <div className='w-7 h-7 md:w-8 md:h-8 rounded-lg bg-secondary flex items-center justify-center text-muted-foreground font-mono text-[10px] border border-border shrink-0'>
                                                    {String(i + 1).padStart(2, '0')}
                                                </div>
                                                <span className='font-semibold text-xs md:text-sm text-foreground/90 truncate'>
                                                    {task}
                                                </span>
                                            </div>
                                            <button
                                                onClick={() => handleCreateTask(task, i)}
                                                disabled={addingTaskId === i}
                                                className='w-7 h-7 md:w-8 md:h-8 rounded-full bg-primary/10 text-primary flex items-center justify-center shrink-0 opacity-100 sm:opacity-0 sm:group-hover:opacity-100 transition-all disabled:opacity-50'
                                            >
                                                {addingTaskId === i ? (
                                                    <RefreshCcw
                                                        size={14}
                                                        className='animate-spin'
                                                    />
                                                ) : (
                                                    <Plus size={14} />
                                                )}
                                            </button>
                                        </motion.div>
                                    ))}
                                </div>
                            )}

                            {activeTab === 'transcript' && result?.tasks && (
                                <div className='space-y-3 md:space-y-4'>
                                    {result.tasks.map((task: any, i: number) => (
                                        <motion.div
                                            key={i}
                                            initial={{ opacity: 0, y: 10 }}
                                            animate={{ opacity: 1, y: 0 }}
                                            transition={{ delay: i * 0.1 }}
                                            className='bg-card border border-border p-4 md:p-6 rounded-2xl flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-l-4 border-l-primary shadow-sm'
                                        >
                                            <div className='flex-1 min-w-0'>
                                                <h4 className='font-bold text-base md:text-lg mb-1 text-foreground truncate'>
                                                    {task.title}
                                                </h4>
                                                <div className='flex flex-wrap items-center gap-3 md:gap-4'>
                                                    <div className='flex items-center gap-1.5 text-muted-foreground text-[10px] md:text-xs'>
                                                        <Users size={12} />
                                                        <span className='truncate'>{task.assignee}</span>
                                                    </div>
                                                    <div className='flex items-center gap-1.5 text-muted-foreground text-[10px] md:text-xs'>
                                                        <Clock size={12} />
                                                        <span className='whitespace-nowrap'>{task.deadline}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <button
                                                onClick={() => handleCreateTask(task.title, i + 100, task)}
                                                disabled={addingTaskId === i + 100}
                                                className='btn-primary w-full sm:w-auto py-2 px-4 text-xs'
                                            >
                                                {addingTaskId === i + 100 ? '...' : 'Create'}
                                            </button>
                                        </motion.div>
                                    ))}
                                </div>
                            )}

                            {activeTab === 'suggest' && result?.suggestions && (
                                <div className='space-y-4'>
                                    <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6'>
                                        {result.suggestions.map((s: any, i: number) => (
                                            <div
                                                key={i}
                                                className='card p-4 md:p-6 border-l-4 border-l-primary bg-secondary/20'
                                            >
                                                <p className='text-[8px] md:text-[10px] font-black uppercase tracking-widest text-muted-foreground mb-1 md:mb-2'>
                                                    Recommendation
                                                </p>
                                                <h4 className='font-bold text-sm md:text-base text-foreground mb-3 truncate'>
                                                    {s.title || 'Selected Task'}
                                                </h4>
                                                <div className='space-y-2'>
                                                    <div className='flex items-center justify-between text-[10px] md:text-xs'>
                                                        <span className='text-muted-foreground'>Priority:</span>
                                                        <span
                                                            className={`font-bold ${s.suggestedPriority === 'High' ? 'text-rose-500' : 'text-primary'}`}
                                                        >
                                                            {s.suggestedPriority}
                                                        </span>
                                                    </div>
                                                    <div className='flex items-center justify-between text-[10px] md:text-xs'>
                                                        <span className='text-muted-foreground'>Deadline:</span>
                                                        <span className='font-bold text-foreground'>
                                                            {new Date(s.suggestedDeadline).toLocaleDateString()}
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {activeTab === 'plan' && result?.phases && (
                                <div className='space-y-6 md:space-y-8'>
                                    {result.phases.map((phase: any, i: number) => (
                                        <div
                                            key={i}
                                            className='card p-5 md:p-8 border border-border bg-secondary/10'
                                        >
                                            <h3 className='text-base md:text-lg font-black uppercase tracking-tight text-primary mb-4 md:mb-6 flex items-center gap-3'>
                                                <div className='w-7 h-7 md:w-8 md:h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary border border-primary/20 text-[10px] md:text-xs shrink-0'>
                                                    {i + 1}
                                                </div>
                                                <span className='truncate'>{phase.name}</span>
                                            </h3>
                                            <div className='grid grid-cols-1 sm:grid-cols-2 gap-3 md:gap-4'>
                                                {phase.tasks.map((task: string, ti: number) => (
                                                    <div
                                                        key={ti}
                                                        className='p-3 md:p-4 bg-background rounded-xl border border-border flex items-center justify-between group gap-2'
                                                    >
                                                        <span className='text-xs md:text-sm font-medium text-foreground/80 truncate'>
                                                            {task}
                                                        </span>
                                                        <button
                                                            onClick={() => handleCreateTask(task, i * 10 + ti)}
                                                            className='opacity-100 sm:opacity-0 sm:group-hover:opacity-100 p-1.5 md:p-2 text-primary hover:bg-primary/5 rounded-lg transition-all shrink-0'
                                                        >
                                                            <Plus size={16} />
                                                        </button>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            )}

                            {activeTab === 'summary' && result && (
                                <div className='grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6'>
                                    <div className='bg-card border border-border p-5 md:p-8 rounded-2xl border-l-4 border-l-emerald-400 shadow-sm'>
                                        <div className='flex items-center gap-3 text-emerald-500 mb-4 md:mb-6'>
                                            <CheckCircle2
                                                size={20}
                                                className='shrink-0'
                                            />
                                            <h3 className='font-black uppercase tracking-widest text-[10px] md:text-xs'>
                                                Status
                                            </h3>
                                        </div>
                                        <p className='text-xs md:text-sm text-foreground/70 leading-relaxed italic'>
                                            {result.summary}
                                        </p>
                                    </div>

                                    <div className='bg-card border border-border p-5 md:p-8 rounded-2xl border-l-4 border-l-amber-400 shadow-sm'>
                                        <div className='flex items-center gap-3 text-amber-500 mb-4 md:mb-6'>
                                            <AlertTriangle
                                                size={20}
                                                className='shrink-0'
                                            />
                                            <h3 className='font-black uppercase tracking-widest text-[10px] md:text-xs'>
                                                Risks
                                            </h3>
                                        </div>
                                        <ul className='space-y-3 md:space-y-4'>
                                            {result.risks?.map((risk: string, i: number) => (
                                                <li
                                                    key={i}
                                                    className='flex gap-2 text-[11px] md:text-sm text-foreground/70'
                                                >
                                                    <span className='text-amber-500 shrink-0'>•</span>
                                                    <span className='truncate'>{risk}</span>
                                                </li>
                                            ))}
                                        </ul>
                                    </div>

                                    <div className='md:col-span-2 bg-card border border-border p-5 md:p-8 rounded-2xl border-l-4 border-l-primary shadow-sm'>
                                        <div className='flex items-center gap-3 text-primary mb-4 md:mb-6'>
                                            <Lightbulb
                                                size={20}
                                                className='shrink-0'
                                            />
                                            <h3 className='font-black uppercase tracking-widest text-[10px] md:text-xs'>
                                                Strategic Steps
                                            </h3>
                                        </div>
                                        <div className='grid grid-cols-1 sm:grid-cols-3 gap-3 md:gap-4'>
                                            {result.nextSteps?.map((step: string, i: number) => (
                                                <div
                                                    key={i}
                                                    className='p-3 md:p-4 rounded-xl bg-secondary border border-border flex items-start gap-3'
                                                >
                                                    <div className='w-5 h-5 md:w-6 md:h-6 rounded-full bg-primary/10 flex items-center justify-center text-primary text-[9px] md:text-[10px] font-bold shrink-0'>
                                                        {i + 1}
                                                    </div>
                                                    <p className='text-[11px] md:text-xs text-foreground/80 font-medium leading-tight'>
                                                        {step}
                                                    </p>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
};

export default AIAssistant;
